export const ERROR_TYPES = {
    "DEFAULT": "SERVER_ERROR",
    "EMAIL_EXISTS": "EMAIL_EXISTS_ERROR",
    "USER_IS_NOT_EXISTS": "USER_IS_NOT_EXISTS_ERROR",
    "ROLE_EXISTS": "ROLE_EXISTS_ERROR",
    "CATEGORY_EXISTS": "CATEGORY_EXISTS_ERROR",
    "PRODUCT_EXISTS": "PRODUCT_EXISTS_ERROR",
    "VALIDATION_ERROR": "VALIDATION_ERROR",
    "AUTH_ERROR": "AUTH_ERROR",
    "FORBIDDEN_ERROR": "FORBIDDEN_ERROR",
};
